#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c
sudo: false

env:
  BYOND_MAJOR="511"
  BYOND_MINOR="1381"
  MACRO_COUNT=4

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (! grep -En "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
  - (! grep 'maps\\.*test.*' *.dme)
  - awk -f tools/indentation.awk **/*.dm
  - md5sum -c - <<< "88490b460c26947f5ec1ab1bb9fa9f17 *html/changelogs/example.yml"
  - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - python tools/TagMatcher/tag-matcher.py ../..
  - echo "#define UNIT_TEST 1" > code/_unit_tests.dm
  - cp config/example/* config/
  - DreamMaker vorestation.dme
  - travis_wait DreamDaemon vorestation.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - grep "All Unit Tests Passed" log.txt

