#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c

env:
  global:
    - BASENAME="vorestation" # $BASENAME.dmb, $BASENAME.dme, etc.
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1513"
    - MACRO_COUNT=4

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - libssl-dev:i386

before_install:
  - chmod -R +x ./tools/travis

install:
  - ./tools/travis/install_byond.sh

before_script:
  - shopt -s globstar

script:
  - ./tools/travis/compile_and_run.sh

# Build-specific settings
jobs:
  include:
    - stage: "File Tests" #This is the odd man out, with specific installs and stuff.
      name: "Validate Files"
      install: #Need python for some of the tag matching stuff
        - pip install --user PyYaml -q
        - pip install --user beautifulsoup4 -q
      script: ./tools/travis/validate_files.sh
      addons:
        apt: 
          packages: ~ # Don't need any packages for this
    - stage: "Unit Tests"
      env: TEST_DEFINE="UNIT_TEST" TEST_FILE="code/_unit_tests.dm" RUN="1"
      name: "Compile normally (unit tests)"
    - stage: "Isolation Tests"
      env: TEST_DEFINE="MAP_TEST" TEST_FILE="code/_map_tests.dm" RUN="0"
      name: "Compile POIs (no run)"
    - env: TEST_DEFINE="AWAY_MISSION_TEST" TEST_FILE="code/_away_mission_tests.dm" RUN="0"
      name: "Compile away missions (no run)"  
    
